/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "error": {
        "ERROR-OCCURRED": string;
        "LOGIN-FAILED": string;
        "DATABASE-ERROR": string;
        "ID-NOT-FOUND": string;
        "PASSWORD-MISMATCH": string;
        "REGISTER-EXIST": string;
        "NOT-FOUND": string;
        "NOT-DATA-SUBSCRIBED": string;
        "INVALID": {
            "TOKEN": string;
        };
        "action": {
            "EXIST-TOKEN": string;
        };
    };
    "property": {
        "LOGIN": string;
        "CAMPAIGN-REPORT": string;
        "CAMPAIGN-SCHEDULE": string;
        "DRAFT": string;
        "USER": string;
        "PUSH-NOTIFICATION": string;
        "USERNAME": string;
    };
    "success": {
        "CREATED-SUCCESS": string;
        "UPDATED-SUCCESS": string;
        "DELETED-SUCCESS": string;
        "SUCCESS": string;
        "PUSH-ALL-SUCCESS": string;
        "ALREADY-SUBSCRIBED": string;
        "UNSUBSCRIBE-SUCCESS": string;
        "USER-REGISTERED-SUCCESS": string;
        "PASSWORD-UPDATED-SUCCESS": string;
        "PASSWORD-RESET-SUCCESS": string;
        "IMAGE-UPLOAD-SUCCESS": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
